[package]
name = "game"
version = "0.1.0"
authors = ["Jeferson Daniel <jeferson.daniel412@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
debug = true
opt-level = 3
lto = true

[dependencies]
gdnative = "0.11.3"
byteorder = "1.4.3"
