[target.wasm32-unknown-emscripten]
rustflags = [
    "-Clink-arg=-sSIDE_MODULE=2", # build a side module that Godot can load
    "-Zlink-native-libraries=no", # workaround for a wasm-ld error during linking
    "-Cpanic=abort", # workaround for a runtime error related to dyncalls
]
