var id: int = 0
var type: String = "normal"
var positionlink: int = 0
var velocity: Vector2 = Vector2(0, 0)
var sin_x: Array = []
var sin_y: Array = []
var spriteno: Array = []
var layerno: int = 0
var start: Vector2 = Vector2(0, 0)
var delta: Vector2 = Vector2(1, 1)
var trans: String = 'none'
var alpha: Vector2 = Vector2(1.0, 1.0)
var mask: int = 0
var tile: Vector2 = Vector2(0, 0)
var tilespacing: Vector2 = Vector2(0, 0)
var window: PoolIntArray = PoolIntArray([])
var windowdelta: Vector2 = Vector2(0, 0)
var actionno: int = 0
var width: Array = []
var top_xscale: float = 1
var bottom_xscale: float = 1
var yscalestart: float = 100
var yscaledelta: float = 1
